# Generated by Django 3.2.8 on 2021-11-01 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='activity_id',
            new_name='activities',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='user_id',
            new_name='users',
        ),
    ]
