# Generated by Django 3.2.8 on 2021-11-01 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_auto_20211101_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='activities',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='users',
            new_name='user',
        ),
    ]
